substitutions:
  device_name: "Balcony1 Heat Pump"
  device_name_id: "balcony1-heat-pump"
  current_res: "0.00221" # Random value. Requires power monitoring calibration
  voltage_div: "955" # Random value. Requires power monitoring calibration
  default_state: ALWAYS_ON

# Enable logging
#debug:

#logger:
#  level: debug

packages:
  ble_tracker: !include "/home/esphome/config/common/templates/template_blitzwolf_shp2_16a.yaml"
