substitutions:
  type: light
  device_name: "Christmas Decorations"
  device_name_id: "christmas-decorations"

# Enable logging
#debug:

#logger:
#  level: debug

packages:
  ble_tracker: !include "/home/esphome/config/common/templates/template_sonoff_basic.yaml"