substitutions:
  device_name: "Christmas Tree"
  device_name_id: "christmas-tree"
  default_state: ALWAYS_OFF

# Enable logging
#debug:

#logger:
#  level: debug

packages:
  ble_tracker: !include "/home/esphome/config/common/templates/template_blitzwolf_shp6_10a.yaml"
