substitutions:
  type: light
  device_name: "Kidsroom1 Cabinet Light"
  device_name_id: "kidsroom1-cabinet-light"

# Enable logging
#debug:

#logger:
#  level: debug

packages:
  ble_tracker: !include "/home/esphome/config/common/templates/template_sonoff_basic.yaml"
