esphome:
  name: wakeup
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Wakeup Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal:
